remove third unused machine
metal-stack/mini-lab pull request #193
Opened 2024-09-19 11:34 UTC by iljarotar

2024-09-19 12:08 UTC, robertvolkmann requested changes

2024-09-19 12:08 UTC, robertvolkmann commented on mini-lab.sonic.yaml
> +    - endpoints: ["leaf02:eth2", "vms:lan5"]
```suggestion
    - endpoints: ["leaf01:eth2", "vms:lan2"]
    - endpoints: ["leaf02:eth2", "vms:lan3"]
```

2024-09-19 14:54 UTC, robertvolkmann approved these changes

2024-09-19 14:54 UTC, merged

2024-09-20 06:25 UTC, Gerrit91 commented on README.md
> +There are three versions, or flavors, of the mini-lab environment which differ in regards to the NOS running on the leaves:
Looks like two? 😅

2024-09-20 07:35 UTC, iljarotar commented on README.md
> +There are three versions, or flavors, of the mini-lab environment which differ in regards to the NOS running on the leaves:
Whoops :smile: